### PR TITLE
[BAD-244] Jobs, CronJobs

### PR DESCRIPTION
**Pull request by Hashfyre**
- adds support for running k8s:`jobs`
- adds an explicit `kind: job / deployment`
- adds `namespace` to `context`
- removes explicit `--namespace` calls from `kubectl` execs

### CODE REVIEW

**Comment by captn3m0** [comment]
@hashfyre what all is pending here?

**Comment by rmenn** [comment]
I believe it was completed, didnt we want to test this somewhere?

**Comment by ace03uec** [comment]
A default needs to be added to ensure steps without kind are treated as `deployments`. 
This has fix has been made as part of the daemonsets PR. 
Those conflicts will have to be resolved.

**Comment by captn3m0** [comment]
@ace03uec can this be closed?

**Comment by captn3m0** [comment]
Moved this to Spinnaker, so closing

**Pull request closed without merging**
